[project]
name = "frictionsegnet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cityscapesscripts>=2.2.4",
    "torch",
    "torchcrf>=1.1.0",
    "torchmetrics>=1.8.2",
    "torchvision",
]
